### ISSUE TITLE
Cannot find name ApplePaySession, ApplePayJS and google when upgrading to 6.8 from 5.68

### ISSUE THREAD

**Issue by bezkom** [Adyen/adyen-web#3162]
`ng serve` is having an issue with the 6.x version of the library, 

`Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:1714:27 - error TS2304: Cannot find name 'ApplePaySession'
1714         ApplePaySession?: ApplePaySession;
Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:1724:43 - error TS2503: Cannot find namespace 'ApplePayJS'.
1752     totalPriceStatus?: ApplePayJS.ApplePayLineItemType;
Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:2515:24 - error TS2503: Cannot find namespace 'google'.
2515     totalPriceStatus?: google.payments.api.TotalPriceStatus;`

probably something I need to change in my tsconfig but I don't know what:

`/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": false,
    "inlineSourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ],
    "types": ["node", "jasmine", "cypress"],
    "allowSyntheticDefaultImports": true,
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  },
  "exclude": [
    "./cypress.config.ts",
    "node_modules",
    "cypress",
  ]
}
`

**Comment by adrianyni** [comment]
Hi @ribeiroguilherme ,

we are currently facing the same issue. To illustrate, I have provided a demo application in a public repository:

https://github.com/adrianyni/adyen-import-error

The application compiles successfully as long as no modules from @adyen/adyen-web are imported. Please uncomment line 3 in “main.ts” to see the errors.

**Comment by ribeiroguilherme** [comment]
Hi guys.

This should be fixed on v6.10.0 . Please let us know if the issue persists.

Cheers
