### PR TITLE
Typescript - Fixing triple slash directives on build file

### LINKED ISSUE #3162: Cannot find name ApplePaySession, ApplePayJS and google when upgrading to 6.8 from 5.68
`ng serve` is having an issue with the 6.x version of the library, 

`Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:1714:27 - error TS2304: Cannot find name 'ApplePaySession'
1714         ApplePaySession?: ApplePaySession;
Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:1724:43 - error TS2503: Cannot find namespace 'ApplePayJS'.
1752     totalPriceStatus?: ApplePayJS.ApplePayLineItemType;
Error: node_modules/@adyen/adyen-web/dist/es/index.d.ts:2515:24 - error TS2503: Cannot find namespace 'google'.
2515     totalPriceStatus?: google.payments.api.TotalPriceStatus;`

probably something I need to change in my tsconfig but I don't know what:

`/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": false,
    "inlineSourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ],
    "types": ["node", "jasmine", "cypress"],
    "allowSyntheticDefaultImports": true,
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  },
  "exclude": [
    "./cypress.config.ts",
    "node_modules",
    "cypress",
  ]
}
`

### PR DESCRIPTION
**Pull request by ribeiroguilherme**
## Summary

The generated types definition didn't contain the references to the googlepay and applepay js types.

For some reason our tsconfig + typescript compiler is not adding the triple slash directives. 

To fix that, I added a script as part of the build types pipeline which add the directives manually. 

Fixes #3162

### CODE REVIEW

File: packages/lib/src/types/custom.d.ts
Comment (ribeiroguilherme) [inline packages/lib/src/types/custom.d.ts:1]: Not sure why this file is in the diff, since it is the same content as the one in the remote

**Review by m1aw — APPROVED** [review]
